config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show] do
    get 'invite'
    get 'uninvite'
    get 'block'
    get 'unblock'
  end

  resources :messages, only: [:create]
  resources :comments, only: [:create]

  root to: "users#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blockade.rb
class Blockade < ApplicationRecord
  belongs_to :user
  belongs_to :blocked_user, class_name: 'User', foreign_key: 'blocked_id'

  validates :user_id, uniqueness: { scope: :blocked_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :message

  validates :user_id, :message_id, :content, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user_id, uniqueness: { scope: :friend_id }

  after_create :create_connected_friendship
  after_destroy :destroy_connected_friendship

  private

  def create_connected_friendship
    Friendship.where(
      user_id: friend_id,
      friend_id: user_id,
      status: 'invited'
    ).first_or_create
  end

  def destroy_connected_friendship
    Friendship.where(
      user_id: friend_id,
      friend_id: user_id
    ).delete_all
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :user_id, :content, presence: true

  def self.created_by(user_ids)
    Message.includes(:user, comments: :user)
           .where(messages: { user_id: user_ids })
           .order('messages.created_at DESC')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages
  has_many :comments

  has_many :friendships
  has_many :friends, through: :friendships

  has_many :by_user_blockades, class_name: 'Blockade', foreign_key: 'user_id'
  has_many :blocked_users, through: :by_user_blockades

  has_many :on_user_blockades, class_name: 'Blockade', foreign_key: 'blocked_id'
  has_many :blocked_by_users, through: :on_user_blockades, source: 'user'

  validates :email,    presence: true
  validates :username, presence: true

  def not_blocked_friends
    blocked_ids = blocked_users.pluck(:id) + blocked_by_users.pluck(:id)
    friends.where.not(id: blocked_ids)
  end

  def all_other_users
    User.where.not(id: id)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def friend_with?(user)
    friends.exists?(id: user.id)
  end

  def blocked?(user)
    blocked_users.exists?(id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end

  def redirect_back_or_default(message = '')
    redirect_back(fallback_location: root_path, alert: message)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = current_user.comments.build(comment_params)
    @info = t('comments.create.failed') unless comment.save
    redirect_back_or_default(@info)
  end

  private

  def comment_params
    params.require(:comment).permit(:message_id, :content)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    message = current_user.messages.build(message_params)
    @info = t('messages.create.failed') unless message.save
    redirect_back_or_default(@info)
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :invite, :uninvite, :block, :unblock]

  def dashboard
    @messages = Message.created_by(for_dashboard_user_ids)
  end

  def show
    redirect_to root_path, alert: t('access_denied') if @user.blocked?(current_user)
    @messages = Message.created_by(@user.id)
  end

  def invite
    friendship = current_user.friendships.build(friend_id: @user.id)
    @info = t('already_invited') unless friendship.save
    redirect_back_or_default(@info)
  end

  def uninvite
    current_user.friends.destroy(@user)
    redirect_back_or_default
  end

  def block
    blockade = current_user.by_user_blockades.build(blocked_id: @user.id)
    @info = t('already_blocked') unless blockade.save
    redirect_back_or_default(@info)
  end

  def unblock
    current_user.blocked_users.destroy(@user)
    redirect_back_or_default
  end

  private

  def set_user
    @user = User.find(params[:id] || params[:user_id])
  end

  def for_dashboard_user_ids
    current_user.not_blocked_friends.distinct.pluck(:id) << current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_list.html.erb
<div class="comments-list">
  <% comments.each do |comment| %>
    <%= render 'comments/single', comment: comment unless current_user.blocked?(comment.user) %>
  <% end %>
</div>

app/views/comments/_new.html.erb
<div class="comment-new">
  <%= form_for(Comment.new) do |f| %>
    <%= f.hidden_field :message_id, value: message.id %>
    <%= f.text_field :content, class: "comment-content" %>
    <%= f.submit 'Comment' %>
  <% end %>
</div>

app/views/comments/_single.html.erb
<div class="comment-single">
  Commented by: <b><%= link_to comment.user.username, comment.user %></b> |
  <%= comment.user.created_at.strftime("%Y/%m/%d at %R") %>
  <br>
  <%= comment.content %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterlike</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <%= render 'shared/flash_messages' %>

      <div class="left-side">
        <div class="header">
          <div class="current-user-info">
            <% if user_signed_in? %>
              Logged in as: <%= current_user.email %> |
              <%= link_to('Home', root_path) %> |
              <%= link_to('Update account', edit_user_registration_path) %> |
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </div>
        </div>

        <%= yield %>
      </div>

      <div class="right-side">
        <% if current_user.present? %>
          <div class="widget-container">
            <div class="widget">
              <h2>Friends:</h2>
              <table>
                <% current_user.friends.each do |user| %>
                  <tr>
                    <td><%= link_to user.username, user %></td>
                    <td></td>
                    <td><%= link_to 'Uninvite', user_uninvite_path(user) %></td>
                  </tr>
                <% end %>
              </table>
            </div>
            <div class="widget">
              <h2>Blocked:</h2>
              <table>
                <% current_user.blocked_users.each do |user| %>
                  <tr>
                    <td><%= link_to user.username, user %></td>
                    <td></td>
                    <td><%= link_to 'Unblock', user_unblock_path(user) %></td>
                  </tr>
                <% end %>
              </table>
            </div>
            <div class="widget">
              <h2>All users:</h2>
              <table>
                <% current_user.all_other_users.each do |user| %>
                  <tr>
                    <td><%= link_to user.username, user %></td>
                    <td><%= link_to 'Invite', user_invite_path(user) %></td>
                    <td><%= link_to 'Block', user_block_path(user) %></td>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>

app/views/messages/_new.html.erb
<div class="message-new">
  <%= form_for(Message.new) do |f| %>
    <%= f.text_field :content, class: "comment-content" %>
    <%= f.submit 'Send message' %>
  <% end %>
</div>

app/views/messages/_single.html.erb
<div class="message-container">
  <div class="single-message">
    Message from: <b><%= link_to message.user.username, message.user %></b> |
    <%= message.user.created_at.strftime("%Y/%m/%d at %R") %>
    <br>
    <%= message.content %>
  </div>
  <%= link_to "Comments", "#", class: "toggle_comments" %>
  <div class="comments-container">
    <%= render 'comments/list', comments: message.comments %>
    <%= render 'comments/new', message: message %>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% if notice.present? || alert.present? %>
  <div class="flash-messages">
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
<% end %>

app/views/users/_message.html.erb
<div class="message-container">
  <div class="single-message">
    <b><%= link_to message.user.username, message.user %></b> |
    <%= message.user.created_at.strftime("%Y/%m/%d at %R") %>
    <br>
    <%= message.content %>
  </div>
  <%= link_to "Comments", "#", class: "toggle_comments" %>
  <div class="comments-container">
    <%= render 'users/comments/new', message: message %>
    <%= render 'users/comments/list', comments: message.comments %>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="content-container">
  <div class="title">
    <h1>Dashboard</h1>
  </div>

  <div class="content">
    <%= render 'messages/new' %>
    <div class="messages-container">
      <% @messages.each do |message| %>
        <%= render 'messages/single', message: message %>
        <br>
      <% end %>
    </div>
  </div>  
</div>

app/views/users/messages/_single.html.erb
<div class="message-container">
  <div class="single-message">
    Message from: <b><%= link_to message.user.username, message.user %></b> |
    <%= message.user.created_at.strftime("%Y/%m/%d at %R") %>
    <br>
    <%= message.content %>
  </div>
  <%= link_to "Comments", "#", class: "toggle_comments" %>
  <div class="comments-container">
    <%= render 'users/comments/list', comments: message.comments %>
    <%= render 'users/comments/new', message: message %>
  </div>
</div>

app/views/users/show.html.erb
<div class="content-container">
  <div class="title">
    <h1>User info:</h1>
      Email: <b><%= @user.email %></b><br>
      Username: <b><%= @user.username %></b><br>
      Full name: <b><%= @user.full_name %></b><br>
      <%= link_to 'Invite', user_invite_path(@user) unless current_user.friend_with?(@user) %> |
      <%= link_to 'Block', user_block_path(@user) unless current_user.blocked?(@user) %>
    <br>
    <h2>User's messages:</h2>
  </div>

  <div class="content">
    <div class="messages-container">
      <% @messages.each do |message| %>
        <%= render 'messages/single', message: message %>
        <br>
      <% end %>
    </div>
  </div>
</div>